-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    usr_id serial NOT NULL,
    usr_name text NOT NULL,
    usr_email text NOT NULL,
    usr_salt text NOT NULL,
    usr_hash text NOT NULL,
    usr_type_id bigint NOT NULL DEFAULT 1,
    usr_country_id bigint NOT NULL DEFAULT 1,
    usr_created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (usr_id)
);

CREATE TABLE IF NOT EXISTS public.user_types
(
    tp_id serial NOT NULL,
    tp_name text NOT NULL,
    PRIMARY KEY (tp_id)
);

CREATE TABLE IF NOT EXISTS public.teams
(
    te_id serial NOT NULL,
    te_name text NOT NULL,
    te_description text NOT NULL,
    te_admin_id bigint NOT NULL,
    te_open boolean NOT NULL,
    te_created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (te_id)
);

CREATE TABLE IF NOT EXISTS public.events
(
    ev_id serial NOT NULL,
    ev_admin_id bigint NOT NULL,
    ev_name text NOT NULL,
    ev_description text NOT NULL,
    ev_date date NOT NULL,
    ev_created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ev_id)
);

CREATE TABLE IF NOT EXISTS public.users_events
(
    users_usr_id serial NOT NULL,
    events_ev_id serial NOT NULL
);

CREATE TABLE IF NOT EXISTS public.countries
(
    cou_id serial NOT NULL,
    cou_name text NOT NULL,
    cou_flag text NOT NULL,
    PRIMARY KEY (cou_id)
);

CREATE TABLE IF NOT EXISTS public.teams_users
(
    tsr_id serial NOT NULL,
    tsr_tea_id bigint NOT NULL,
    tsr_usr_id bigint NOT NULL,
    PRIMARY KEY (tsr_id)
);

ALTER TABLE IF EXISTS public.users
    ADD FOREIGN KEY (usr_type_id)
    REFERENCES public.user_types (tp_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.users
    ADD FOREIGN KEY (usr_country_id)
    REFERENCES public.countries (cou_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.users_events
    ADD FOREIGN KEY (users_usr_id)
    REFERENCES public.users (usr_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.users_events
    ADD FOREIGN KEY (events_ev_id)
    REFERENCES public.events (ev_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.teams_users
    ADD FOREIGN KEY (tsr_tea_id)
    REFERENCES public.teams (te_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.teams_users
    ADD FOREIGN KEY (tsr_usr_id)
    REFERENCES public.users (usr_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;