-- insert types
insert into user_types (tp_name) values ('Personal');
insert into user_types (tp_name) values ('Organizational Entity');

-- insert coutries
insert into countries (cou_name, cou_flag) values ('International', '🏳️');
insert into countries (cou_name, cou_flag) values ('Malaysia', '🇲🇾');
insert into countries (cou_name, cou_flag) values ('Haiti', '🇭🇹');
insert into countries (cou_name, cou_flag) values ('Tajikistan', '🇹🇯');
insert into countries (cou_name, cou_flag) values ('American Samoa', '🇦🇸');
insert into countries (cou_name, cou_flag) values ('Italy', '🇮🇹');
insert into countries (cou_name, cou_flag) values ('Mexico', '🇲🇽');
insert into countries (cou_name, cou_flag) values ('North Macedonia', '🇲🇰');
insert into countries (cou_name, cou_flag) values ('Samoa', '🇼🇸');
insert into countries (cou_name, cou_flag) values ('Guernsey', '🇬🇬');
insert into countries (cou_name, cou_flag) values ('Laos', '🇱🇦');
insert into countries (cou_name, cou_flag) values ('Namibia', '🇳🇦');
insert into countries (cou_name, cou_flag) values ('British Virgin Islands', '🇻🇬');
insert into countries (cou_name, cou_flag) values ('Cayman Islands', '🇰🇾');
insert into countries (cou_name, cou_flag) values ('Egypt', '🇪🇬');
insert into countries (cou_name, cou_flag) values ('Cambodia', '🇰🇭');
insert into countries (cou_name, cou_flag) values ('Cook Islands', '🇨🇰');
insert into countries (cou_name, cou_flag) values ('Seychelles', '🇸🇨');
insert into countries (cou_name, cou_flag) values ('Israel', '🇮🇱');
insert into countries (cou_name, cou_flag) values ('Bolivia', '🇧🇴');
insert into countries (cou_name, cou_flag) values ('Åland Islands', '🇦🇽');
insert into countries (cou_name, cou_flag) values ('United Arab Emirates', '🇦🇪');
insert into countries (cou_name, cou_flag) values ('Grenada', '🇬🇩');
insert into countries (cou_name, cou_flag) values ('China', '🇨🇳');
insert into countries (cou_name, cou_flag) values ('Greenland', '🇬🇱');
insert into countries (cou_name, cou_flag) values ('Vatican City', '🇻🇦');
insert into countries (cou_name, cou_flag) values ('Vanuatu', '🇻🇺');
insert into countries (cou_name, cou_flag) values ('Nauru', '🇳🇷');
insert into countries (cou_name, cou_flag) values ('Micronesia', '🇫🇲');
insert into countries (cou_name, cou_flag) values ('Solomon Islands', '🇸🇧');
insert into countries (cou_name, cou_flag) values ('United States Virgin Islands', '🇻🇮');
insert into countries (cou_name, cou_flag) values ('Turkey', '🇹🇷');
insert into countries (cou_name, cou_flag) values ('Kuwait', '🇰🇼');
insert into countries (cou_name, cou_flag) values ('Senegal', '🇸🇳');
insert into countries (cou_name, cou_flag) values ('Burundi', '🇧🇮');
insert into countries (cou_name, cou_flag) values ('Serbia', '🇷🇸');
insert into countries (cou_name, cou_flag) values ('Brunei', '🇧🇳');
insert into countries (cou_name, cou_flag) values ('Heard Island and McDonald Islands', '🇭🇲');
insert into countries (cou_name, cou_flag) values ('Bahamas', '🇧🇸');
insert into countries (cou_name, cou_flag) values ('Bahrain', '🇧🇭');
insert into countries (cou_name, cou_flag) values ('Dominican Republic', '🇩🇴');
insert into countries (cou_name, cou_flag) values ('Curaçao', '🇨🇼');
insert into countries (cou_name, cou_flag) values ('Norfolk Island', '🇳🇫');
insert into countries (cou_name, cou_flag) values ('North Korea', '🇰🇵');
insert into countries (cou_name, cou_flag) values ('Tokelau', '🇹🇰');
insert into countries (cou_name, cou_flag) values ('South Sudan', '🇸🇸');
insert into countries (cou_name, cou_flag) values ('Aruba', '🇦🇼');
insert into countries (cou_name, cou_flag) values ('Czechia', '🇨🇿');
insert into countries (cou_name, cou_flag) values ('Guadeloupe', '🇬🇵');
insert into countries (cou_name, cou_flag) values ('Syria', '🇸🇾');
insert into countries (cou_name, cou_flag) values ('Marshall Islands', '🇲🇭');
insert into countries (cou_name, cou_flag) values ('Tanzania', '🇹🇿');
insert into countries (cou_name, cou_flag) values ('Papua New Guinea', '🇵🇬');
insert into countries (cou_name, cou_flag) values ('Eritrea', '🇪🇷');
insert into countries (cou_name, cou_flag) values ('Moldova', '🇲🇩');
insert into countries (cou_name, cou_flag) values ('Uzbekistan', '🇺🇿');
insert into countries (cou_name, cou_flag) values ('France', '🇫🇷');
insert into countries (cou_name, cou_flag) values ('Uruguay', '🇺🇾');
insert into countries (cou_name, cou_flag) values ('DR Congo', '🇨🇩');
insert into countries (cou_name, cou_flag) values ('Saint Lucia', '🇱🇨');
insert into countries (cou_name, cou_flag) values ('Tuvalu', '🇹🇻');
insert into countries (cou_name, cou_flag) values ('Canada', '🇨🇦');
insert into countries (cou_name, cou_flag) values ('Switzerland', '🇨🇭');
insert into countries (cou_name, cou_flag) values ('Gabon', '🇬🇦');
insert into countries (cou_name, cou_flag) values ('Libya', '🇱🇾');
insert into countries (cou_name, cou_flag) values ('Monaco', '🇲🇨');
insert into countries (cou_name, cou_flag) values ('United Kingdom', '🇬🇧');
insert into countries (cou_name, cou_flag) values ('Rwanda', '🇷🇼');
insert into countries (cou_name, cou_flag) values ('Bhutan', '🇧🇹');
insert into countries (cou_name, cou_flag) values ('Saint Barthélemy', '🇧🇱');
insert into countries (cou_name, cou_flag) values ('Botswana', '🇧🇼');
insert into countries (cou_name, cou_flag) values ('India', '🇮🇳');
insert into countries (cou_name, cou_flag) values ('New Zealand', '🇳🇿');
insert into countries (cou_name, cou_flag) values ('Ireland', '🇮🇪');
insert into countries (cou_name, cou_flag) values ('Macau', '🇲🇴');
insert into countries (cou_name, cou_flag) values ('New Caledonia', '🇳🇨');
insert into countries (cou_name, cou_flag) values ('Bulgaria', '🇧🇬');
insert into countries (cou_name, cou_flag) values ('Eswatini', '🇸🇿');
insert into countries (cou_name, cou_flag) values ('Algeria', '🇩🇿');
insert into countries (cou_name, cou_flag) values ('Kenya', '🇰🇪');
insert into countries (cou_name, cou_flag) values ('Mali', '🇲🇱');
insert into countries (cou_name, cou_flag) values ('Venezuela', '🇻🇪');
insert into countries (cou_name, cou_flag) values ('Bosnia and Herzegovina', '🇧🇦');
insert into countries (cou_name, cou_flag) values ('Somalia', '🇸🇴');
insert into countries (cou_name, cou_flag) values ('Norway', '🇳🇴');
insert into countries (cou_name, cou_flag) values ('Gambia', '🇬🇲');
insert into countries (cou_name, cou_flag) values ('Estonia', '🇪🇪');
insert into countries (cou_name, cou_flag) values ('Belize', '🇧🇿');
insert into countries (cou_name, cou_flag) values ('Paraguay', '🇵🇾');
insert into countries (cou_name, cou_flag) values ('Guinea', '🇬🇳');
insert into countries (cou_name, cou_flag) values ('Luxembourg', '🇱🇺');
insert into countries (cou_name, cou_flag) values ('South Africa', '🇿🇦');
insert into countries (cou_name, cou_flag) values ('Jordan', '🇯🇴');
insert into countries (cou_name, cou_flag) values ('Timor-Leste', '🇹🇱');
insert into countries (cou_name, cou_flag) values ('Zimbabwe', '🇿🇼');
insert into countries (cou_name, cou_flag) values ('Mozambique', '🇲🇿');
insert into countries (cou_name, cou_flag) values ('Caribbean Netherlands', '');
insert into countries (cou_name, cou_flag) values ('Chile', '🇨🇱');
insert into countries (cou_name, cou_flag) values ('Germany', '🇩🇪');
insert into countries (cou_name, cou_flag) values ('El Salvador', '🇸🇻');
insert into countries (cou_name, cou_flag) values ('Guatemala', '🇬🇹');
insert into countries (cou_name, cou_flag) values ('Lesotho', '🇱🇸');
insert into countries (cou_name, cou_flag) values ('Peru', '🇵🇪');
insert into countries (cou_name, cou_flag) values ('Sint Maarten', '🇸🇽');
insert into countries (cou_name, cou_flag) values ('Djibouti', '🇩🇯');
insert into countries (cou_name, cou_flag) values ('French Southern and Antarctic Lands', '🇹🇫');
insert into countries (cou_name, cou_flag) values ('Australia', '🇦🇺');
insert into countries (cou_name, cou_flag) values ('Chad', '🇹🇩');
insert into countries (cou_name, cou_flag) values ('São Tomé and Príncipe', '🇸🇹');
insert into countries (cou_name, cou_flag) values ('United States', '🇺🇸');
insert into countries (cou_name, cou_flag) values ('Spain', '🇪🇸');
insert into countries (cou_name, cou_flag) values ('Azerbaijan', '🇦🇿');
insert into countries (cou_name, cou_flag) values ('Denmark', '🇩🇰');
insert into countries (cou_name, cou_flag) values ('Fiji', '🇫🇯');
insert into countries (cou_name, cou_flag) values ('Poland', '🇵🇱');
insert into countries (cou_name, cou_flag) values ('Sierra Leone', '🇸🇱');
insert into countries (cou_name, cou_flag) values ('Palestine', '🇵🇸');
insert into countries (cou_name, cou_flag) values ('Mauritania', '🇲🇷');
insert into countries (cou_name, cou_flag) values ('Russia', '🇷🇺');
insert into countries (cou_name, cou_flag) values ('Malta', '🇲🇹');
insert into countries (cou_name, cou_flag) values ('Nicaragua', '🇳🇮');
insert into countries (cou_name, cou_flag) values ('Svalbard and Jan Mayen', '🇸🇯');
insert into countries (cou_name, cou_flag) values ('San Marino', '🇸🇲');
insert into countries (cou_name, cou_flag) values ('Ghana', '🇬🇭');
insert into countries (cou_name, cou_flag) values ('Honduras', '🇭🇳');
insert into countries (cou_name, cou_flag) values ('Maldives', '🇲🇻');
insert into countries (cou_name, cou_flag) values ('Nepal', '🇳🇵');
insert into countries (cou_name, cou_flag) values ('Taiwan', '🇹🇼');
insert into countries (cou_name, cou_flag) values ('Niger', '🇳🇪');
insert into countries (cou_name, cou_flag) values ('Slovakia', '🇸🇰');
insert into countries (cou_name, cou_flag) values ('Lebanon', '🇱🇧');
insert into countries (cou_name, cou_flag) values ('Oman', '🇴🇲');
insert into countries (cou_name, cou_flag) values ('Niue', '🇳🇺');
insert into countries (cou_name, cou_flag) values ('Anguilla', '🇦🇮');
insert into countries (cou_name, cou_flag) values ('Singapore', '🇸🇬');
insert into countries (cou_name, cou_flag) values ('Ivory Coast', '🇨🇮');
insert into countries (cou_name, cou_flag) values ('Kosovo', '🇽🇰');
insert into countries (cou_name, cou_flag) values ('Jersey', '🇯🇪');
insert into countries (cou_name, cou_flag) values ('Romania', '🇷🇴');
insert into countries (cou_name, cou_flag) values ('Slovenia', '🇸🇮');
insert into countries (cou_name, cou_flag) values ('Isle of Man', '🇮🇲');
insert into countries (cou_name, cou_flag) values ('Belarus', '🇧🇾');
insert into countries (cou_name, cou_flag) values ('Cuba', '🇨🇺');
insert into countries (cou_name, cou_flag) values ('Montserrat', '🇲🇸');
insert into countries (cou_name, cou_flag) values ('Montenegro', '🇲🇪');
insert into countries (cou_name, cou_flag) values ('Kiribati', '🇰🇮');
insert into countries (cou_name, cou_flag) values ('Liechtenstein', '🇱🇮');
insert into countries (cou_name, cou_flag) values ('Palau', '🇵🇼');
insert into countries (cou_name, cou_flag) values ('Réunion', '🇷🇪');
insert into countries (cou_name, cou_flag) values ('Saint Martin', '🇲🇫');
insert into countries (cou_name, cou_flag) values ('Pitcairn Islands', '🇵🇳');
insert into countries (cou_name, cou_flag) values ('Falkland Islands', '🇫🇰');
insert into countries (cou_name, cou_flag) values ('Sweden', '🇸🇪');
insert into countries (cou_name, cou_flag) values ('Hungary', '🇭🇺');
insert into countries (cou_name, cou_flag) values ('Morocco', '🇲🇦');
insert into countries (cou_name, cou_flag) values ('Colombia', '🇨🇴');
insert into countries (cou_name, cou_flag) values ('Sudan', '🇸🇩');
insert into countries (cou_name, cou_flag) values ('Hong Kong', '🇭🇰');
insert into countries (cou_name, cou_flag) values ('Saint Helena, Ascension and Tristan da Cunha', '🇸🇭');
insert into countries (cou_name, cou_flag) values ('Turkmenistan', '🇹🇲');
insert into countries (cou_name, cou_flag) values ('Togo', '🇹🇬');
insert into countries (cou_name, cou_flag) values ('Argentina', '🇦🇷');
insert into countries (cou_name, cou_flag) values ('Saudi Arabia', '🇸🇦');
insert into countries (cou_name, cou_flag) values ('Bermuda', '🇧🇲');
insert into countries (cou_name, cou_flag) values ('Ecuador', '🇪🇨');
insert into countries (cou_name, cou_flag) values ('Ethiopia', '🇪🇹');
insert into countries (cou_name, cou_flag) values ('Saint Kitts and Nevis', '🇰🇳');
insert into countries (cou_name, cou_flag) values ('Mauritius', '🇲🇺');
insert into countries (cou_name, cou_flag) values ('Netherlands', '🇳🇱');
insert into countries (cou_name, cou_flag) values ('Myanmar', '🇲🇲');
insert into countries (cou_name, cou_flag) values ('Cocos (Keeling) Islands', '🇨🇨');
insert into countries (cou_name, cou_flag) values ('Liberia', '🇱🇷');
insert into countries (cou_name, cou_flag) values ('Turks and Caicos Islands', '🇹🇨');
insert into countries (cou_name, cou_flag) values ('Tunisia', '🇹🇳');
insert into countries (cou_name, cou_flag) values ('Western Sahara', '🇪🇭');
insert into countries (cou_name, cou_flag) values ('Finland', '🇫🇮');
insert into countries (cou_name, cou_flag) values ('Iceland', '🇮🇸');
insert into countries (cou_name, cou_flag) values ('Northern Mariana Islands', '🇲🇵');
insert into countries (cou_name, cou_flag) values ('Guam', '🇬🇺');
insert into countries (cou_name, cou_flag) values ('Jamaica', '🇯🇲');
insert into countries (cou_name, cou_flag) values ('Burkina Faso', '🇧🇫');
insert into countries (cou_name, cou_flag) values ('Antigua and Barbuda', '🇦🇬');
insert into countries (cou_name, cou_flag) values ('Mongolia', '🇲🇳');
insert into countries (cou_name, cou_flag) values ('Benin', '🇧🇯');
insert into countries (cou_name, cou_flag) values ('Indonesia', '🇮🇩');
insert into countries (cou_name, cou_flag) values ('Georgia', '🇬🇪');
insert into countries (cou_name, cou_flag) values ('Albania', '🇦🇱');
insert into countries (cou_name, cou_flag) values ('Brazil', '🇧🇷');
insert into countries (cou_name, cou_flag) values ('Gibraltar', '🇬🇮');
insert into countries (cou_name, cou_flag) values ('Saint Vincent and the Grenadines', '🇻🇨');
insert into countries (cou_name, cou_flag) values ('Iran', '🇮🇷');
insert into countries (cou_name, cou_flag) values ('Portugal', '🇵🇹');
insert into countries (cou_name, cou_flag) values ('Cameroon', '🇨🇲');
insert into countries (cou_name, cou_flag) values ('Dominica', '🇩🇲');
insert into countries (cou_name, cou_flag) values ('Nigeria', '🇳🇬');
insert into countries (cou_name, cou_flag) values ('South Korea', '🇰🇷');
insert into countries (cou_name, cou_flag) values ('Angola', '🇦🇴');
insert into countries (cou_name, cou_flag) values ('Comoros', '🇰🇲');
insert into countries (cou_name, cou_flag) values ('Greece', '🇬🇷');
insert into countries (cou_name, cou_flag) values ('Belgium', '🇧🇪');
insert into countries (cou_name, cou_flag) values ('Puerto Rico', '🇵🇷');
insert into countries (cou_name, cou_flag) values ('Republic of the Congo', '🇨🇬');
insert into countries (cou_name, cou_flag) values ('Barbados', '🇧🇧');
insert into countries (cou_name, cou_flag) values ('Antarctica', '🇦🇶');
insert into countries (cou_name, cou_flag) values ('Equatorial Guinea', '🇬🇶');
insert into countries (cou_name, cou_flag) values ('Thailand', '🇹🇭');
insert into countries (cou_name, cou_flag) values ('Christmas Island', '🇨🇽');
insert into countries (cou_name, cou_flag) values ('Guinea-Bissau', '🇬🇼');
insert into countries (cou_name, cou_flag) values ('Panama', '🇵🇦');
insert into countries (cou_name, cou_flag) values ('Latvia', '🇱🇻');
insert into countries (cou_name, cou_flag) values ('Guyana', '🇬🇾');
insert into countries (cou_name, cou_flag) values ('Lithuania', '🇱🇹');
insert into countries (cou_name, cou_flag) values ('Yemen', '🇾🇪');
insert into countries (cou_name, cou_flag) values ('Martinique', '🇲🇶');
insert into countries (cou_name, cou_flag) values ('French Guiana', '🇬🇫');
insert into countries (cou_name, cou_flag) values ('Suriname', '🇸🇷');
insert into countries (cou_name, cou_flag) values ('United States Minor Outlying Islands', '🇺🇲');
insert into countries (cou_name, cou_flag) values ('Cyprus', '🇨🇾');
insert into countries (cou_name, cou_flag) values ('Cape Verde', '🇨🇻');
insert into countries (cou_name, cou_flag) values ('Wallis and Futuna', '🇼🇫');
insert into countries (cou_name, cou_flag) values ('Mayotte', '🇾🇹');
insert into countries (cou_name, cou_flag) values ('Vietnam', '🇻🇳');
insert into countries (cou_name, cou_flag) values ('French Polynesia', '🇵🇫');
insert into countries (cou_name, cou_flag) values ('Trinidad and Tobago', '🇹🇹');
insert into countries (cou_name, cou_flag) values ('Malawi', '🇲🇼');
insert into countries (cou_name, cou_flag) values ('Croatia', '🇭🇷');
insert into countries (cou_name, cou_flag) values ('Madagascar', '🇲🇬');
insert into countries (cou_name, cou_flag) values ('Armenia', '🇦🇲');
insert into countries (cou_name, cou_flag) values ('Austria', '🇦🇹');
insert into countries (cou_name, cou_flag) values ('Saint Pierre and Miquelon', '🇵🇲');
insert into countries (cou_name, cou_flag) values ('Afghanistan', '🇦🇫');
insert into countries (cou_name, cou_flag) values ('Central African Republic', '🇨🇫');
insert into countries (cou_name, cou_flag) values ('Zambia', '🇿🇲');
insert into countries (cou_name, cou_flag) values ('Bangladesh', '🇧🇩');
insert into countries (cou_name, cou_flag) values ('Costa Rica', '🇨🇷');
insert into countries (cou_name, cou_flag) values ('Faroe Islands', '🇫🇴');
insert into countries (cou_name, cou_flag) values ('Uganda', '🇺🇬');
insert into countries (cou_name, cou_flag) values ('Kazakhstan', '🇰🇿');
insert into countries (cou_name, cou_flag) values ('Bouvet Island', '🇧🇻');
insert into countries (cou_name, cou_flag) values ('South Georgia', '🇬🇸');
insert into countries (cou_name, cou_flag) values ('Tonga', '🇹🇴');
insert into countries (cou_name, cou_flag) values ('Ukraine', '🇺🇦');
insert into countries (cou_name, cou_flag) values ('Qatar', '🇶🇦');
insert into countries (cou_name, cou_flag) values ('Andorra', '🇦🇩');
insert into countries (cou_name, cou_flag) values ('Iraq', '🇮🇶');
insert into countries (cou_name, cou_flag) values ('Sri Lanka', '🇱🇰');
insert into countries (cou_name, cou_flag) values ('Japan', '🇯🇵');
insert into countries (cou_name, cou_flag) values ('Kyrgyzstan', '🇰🇬');
insert into countries (cou_name, cou_flag) values ('Philippines', '🇵🇭');
insert into countries (cou_name, cou_flag) values ('Pakistan', '🇵🇰');
insert into countries (cou_name, cou_flag) values ('British Indian Ocean Territory', '🇮🇴');


-- insert users (senhas: 123456)
insert into users (usr_name, usr_email, usr_password, usr_type_id, usr_country_id) values ('Felipe', 'felipe@email.com', '$2b$10$Be.y7oUVh6xWYTeHX.Nyh.7eJ3hR35gH47VYWH4ERmtFpX1fFVDke', 1, 188);
insert into users (usr_name, usr_email, usr_password, usr_type_id, usr_country_id) values ('Luis', 'luis@email.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', 1, 188);
insert into users (usr_name, usr_email, usr_password, usr_type_id, usr_country_id) values ('Willian', 'willian@email.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', 1, 188);

-- insert teams
--insert into teams (te_name, te_description, te_admin_id, te_open) values ('Elite Runners', '...', 1, true);

-- insert team users
--insert into teams_users (tsr_tea_id, tsr_usr_id) values (1, 1);
--insert into teams_users (tsr_tea_id, tsr_usr_id) values (1, 2);

commit;
