-- insert coutries
insert into countries (cou_name, cou_flag) values ('International', '🏳️');
insert into countries (cou_name, cou_flag) values ('Malaysia', '🇲🇾');
insert into countries (cou_name, cou_flag) values ('Haiti', '🇭🇹');
insert into countries (cou_name, cou_flag) values ('Tajikistan', '🇹🇯');
insert into countries (cou_name, cou_flag) values ('American Samoa', '🇦🇸');
insert into countries (cou_name, cou_flag) values ('Italy', '🇮🇹');
insert into countries (cou_name, cou_flag) values ('Mexico', '🇲🇽');
insert into countries (cou_name, cou_flag) values ('North Macedonia', '🇲🇰');
insert into countries (cou_name, cou_flag) values ('Samoa', '🇼🇸');
insert into countries (cou_name, cou_flag) values ('Guernsey', '🇬🇬');
insert into countries (cou_name, cou_flag) values ('Laos', '🇱🇦');
insert into countries (cou_name, cou_flag) values ('Namibia', '🇳🇦');
insert into countries (cou_name, cou_flag) values ('British Virgin Islands', '🇻🇬');
insert into countries (cou_name, cou_flag) values ('Cayman Islands', '🇰🇾');
insert into countries (cou_name, cou_flag) values ('Egypt', '🇪🇬');
insert into countries (cou_name, cou_flag) values ('Cambodia', '🇰🇭');
insert into countries (cou_name, cou_flag) values ('Cook Islands', '🇨🇰');
insert into countries (cou_name, cou_flag) values ('Seychelles', '🇸🇨');
insert into countries (cou_name, cou_flag) values ('Israel', '🇮🇱');
insert into countries (cou_name, cou_flag) values ('Bolivia', '🇧🇴');
insert into countries (cou_name, cou_flag) values ('Åland Islands', '🇦🇽');
insert into countries (cou_name, cou_flag) values ('United Arab Emirates', '🇦🇪');
insert into countries (cou_name, cou_flag) values ('Grenada', '🇬🇩');
insert into countries (cou_name, cou_flag) values ('China', '🇨🇳');
insert into countries (cou_name, cou_flag) values ('Greenland', '🇬🇱');
insert into countries (cou_name, cou_flag) values ('Vatican City', '🇻🇦');
insert into countries (cou_name, cou_flag) values ('Vanuatu', '🇻🇺');
insert into countries (cou_name, cou_flag) values ('Nauru', '🇳🇷');
insert into countries (cou_name, cou_flag) values ('Micronesia', '🇫🇲');
insert into countries (cou_name, cou_flag) values ('Solomon Islands', '🇸🇧');
insert into countries (cou_name, cou_flag) values ('United States Virgin Islands', '🇻🇮');
insert into countries (cou_name, cou_flag) values ('Turkey', '🇹🇷');
insert into countries (cou_name, cou_flag) values ('Kuwait', '🇰🇼');
insert into countries (cou_name, cou_flag) values ('Senegal', '🇸🇳');
insert into countries (cou_name, cou_flag) values ('Burundi', '🇧🇮');
insert into countries (cou_name, cou_flag) values ('Serbia', '🇷🇸');
insert into countries (cou_name, cou_flag) values ('Brunei', '🇧🇳');
insert into countries (cou_name, cou_flag) values ('Heard Island and McDonald Islands', '🇭🇲');
insert into countries (cou_name, cou_flag) values ('Bahamas', '🇧🇸');
insert into countries (cou_name, cou_flag) values ('Bahrain', '🇧🇭');
insert into countries (cou_name, cou_flag) values ('Dominican Republic', '🇩🇴');
insert into countries (cou_name, cou_flag) values ('Curaçao', '🇨🇼');
insert into countries (cou_name, cou_flag) values ('Norfolk Island', '🇳🇫');
insert into countries (cou_name, cou_flag) values ('North Korea', '🇰🇵');
insert into countries (cou_name, cou_flag) values ('Tokelau', '🇹🇰');
insert into countries (cou_name, cou_flag) values ('South Sudan', '🇸🇸');
insert into countries (cou_name, cou_flag) values ('Aruba', '🇦🇼');
insert into countries (cou_name, cou_flag) values ('Czechia', '🇨🇿');
insert into countries (cou_name, cou_flag) values ('Guadeloupe', '🇬🇵');
insert into countries (cou_name, cou_flag) values ('Syria', '🇸🇾');
insert into countries (cou_name, cou_flag) values ('Marshall Islands', '🇲🇭');
insert into countries (cou_name, cou_flag) values ('Tanzania', '🇹🇿');
insert into countries (cou_name, cou_flag) values ('Papua New Guinea', '🇵🇬');
insert into countries (cou_name, cou_flag) values ('Eritrea', '🇪🇷');
insert into countries (cou_name, cou_flag) values ('Moldova', '🇲🇩');
insert into countries (cou_name, cou_flag) values ('Uzbekistan', '🇺🇿');
insert into countries (cou_name, cou_flag) values ('France', '🇫🇷');
insert into countries (cou_name, cou_flag) values ('Uruguay', '🇺🇾');
insert into countries (cou_name, cou_flag) values ('DR Congo', '🇨🇩');
insert into countries (cou_name, cou_flag) values ('Saint Lucia', '🇱🇨');
insert into countries (cou_name, cou_flag) values ('Tuvalu', '🇹🇻');
insert into countries (cou_name, cou_flag) values ('Canada', '🇨🇦');
insert into countries (cou_name, cou_flag) values ('Switzerland', '🇨🇭');
insert into countries (cou_name, cou_flag) values ('Gabon', '🇬🇦');
insert into countries (cou_name, cou_flag) values ('Libya', '🇱🇾');
insert into countries (cou_name, cou_flag) values ('Monaco', '🇲🇨');
insert into countries (cou_name, cou_flag) values ('United Kingdom', '🇬🇧');
insert into countries (cou_name, cou_flag) values ('Rwanda', '🇷🇼');
insert into countries (cou_name, cou_flag) values ('Bhutan', '🇧🇹');
insert into countries (cou_name, cou_flag) values ('Saint Barthélemy', '🇧🇱');
insert into countries (cou_name, cou_flag) values ('Botswana', '🇧🇼');
insert into countries (cou_name, cou_flag) values ('India', '🇮🇳');
insert into countries (cou_name, cou_flag) values ('New Zealand', '🇳🇿');
insert into countries (cou_name, cou_flag) values ('Ireland', '🇮🇪');
insert into countries (cou_name, cou_flag) values ('Macau', '🇲🇴');
insert into countries (cou_name, cou_flag) values ('New Caledonia', '🇳🇨');
insert into countries (cou_name, cou_flag) values ('Bulgaria', '🇧🇬');
insert into countries (cou_name, cou_flag) values ('Eswatini', '🇸🇿');
insert into countries (cou_name, cou_flag) values ('Algeria', '🇩🇿');
insert into countries (cou_name, cou_flag) values ('Kenya', '🇰🇪');
insert into countries (cou_name, cou_flag) values ('Mali', '🇲🇱');
insert into countries (cou_name, cou_flag) values ('Venezuela', '🇻🇪');
insert into countries (cou_name, cou_flag) values ('Bosnia and Herzegovina', '🇧🇦');
insert into countries (cou_name, cou_flag) values ('Somalia', '🇸🇴');
insert into countries (cou_name, cou_flag) values ('Norway', '🇳🇴');
insert into countries (cou_name, cou_flag) values ('Gambia', '🇬🇲');
insert into countries (cou_name, cou_flag) values ('Estonia', '🇪🇪');
insert into countries (cou_name, cou_flag) values ('Belize', '🇧🇿');
insert into countries (cou_name, cou_flag) values ('Paraguay', '🇵🇾');
insert into countries (cou_name, cou_flag) values ('Guinea', '🇬🇳');
insert into countries (cou_name, cou_flag) values ('Luxembourg', '🇱🇺');
insert into countries (cou_name, cou_flag) values ('South Africa', '🇿🇦');
insert into countries (cou_name, cou_flag) values ('Jordan', '🇯🇴');
insert into countries (cou_name, cou_flag) values ('Timor-Leste', '🇹🇱');
insert into countries (cou_name, cou_flag) values ('Zimbabwe', '🇿🇼');
insert into countries (cou_name, cou_flag) values ('Mozambique', '🇲🇿');
insert into countries (cou_name, cou_flag) values ('Caribbean Netherlands', '');
insert into countries (cou_name, cou_flag) values ('Chile', '🇨🇱');
insert into countries (cou_name, cou_flag) values ('Germany', '🇩🇪');
insert into countries (cou_name, cou_flag) values ('El Salvador', '🇸🇻');
insert into countries (cou_name, cou_flag) values ('Guatemala', '🇬🇹');
insert into countries (cou_name, cou_flag) values ('Lesotho', '🇱🇸');
insert into countries (cou_name, cou_flag) values ('Peru', '🇵🇪');
insert into countries (cou_name, cou_flag) values ('Sint Maarten', '🇸🇽');
insert into countries (cou_name, cou_flag) values ('Djibouti', '🇩🇯');
insert into countries (cou_name, cou_flag) values ('French Southern and Antarctic Lands', '🇹🇫');
insert into countries (cou_name, cou_flag) values ('Australia', '🇦🇺');
insert into countries (cou_name, cou_flag) values ('Chad', '🇹🇩');
insert into countries (cou_name, cou_flag) values ('São Tomé and Príncipe', '🇸🇹');
insert into countries (cou_name, cou_flag) values ('United States', '🇺🇸');
insert into countries (cou_name, cou_flag) values ('Spain', '🇪🇸');
insert into countries (cou_name, cou_flag) values ('Azerbaijan', '🇦🇿');
insert into countries (cou_name, cou_flag) values ('Denmark', '🇩🇰');
insert into countries (cou_name, cou_flag) values ('Fiji', '🇫🇯');
insert into countries (cou_name, cou_flag) values ('Poland', '🇵🇱');
insert into countries (cou_name, cou_flag) values ('Sierra Leone', '🇸🇱');
insert into countries (cou_name, cou_flag) values ('Palestine', '🇵🇸');
insert into countries (cou_name, cou_flag) values ('Mauritania', '🇲🇷');
insert into countries (cou_name, cou_flag) values ('Russia', '🇷🇺');
insert into countries (cou_name, cou_flag) values ('Malta', '🇲🇹');
insert into countries (cou_name, cou_flag) values ('Nicaragua', '🇳🇮');
insert into countries (cou_name, cou_flag) values ('Svalbard and Jan Mayen', '🇸🇯');
insert into countries (cou_name, cou_flag) values ('San Marino', '🇸🇲');
insert into countries (cou_name, cou_flag) values ('Ghana', '🇬🇭');
insert into countries (cou_name, cou_flag) values ('Honduras', '🇭🇳');
insert into countries (cou_name, cou_flag) values ('Maldives', '🇲🇻');
insert into countries (cou_name, cou_flag) values ('Nepal', '🇳🇵');
insert into countries (cou_name, cou_flag) values ('Taiwan', '🇹🇼');
insert into countries (cou_name, cou_flag) values ('Niger', '🇳🇪');
insert into countries (cou_name, cou_flag) values ('Slovakia', '🇸🇰');
insert into countries (cou_name, cou_flag) values ('Lebanon', '🇱🇧');
insert into countries (cou_name, cou_flag) values ('Oman', '🇴🇲');
insert into countries (cou_name, cou_flag) values ('Niue', '🇳🇺');
insert into countries (cou_name, cou_flag) values ('Anguilla', '🇦🇮');
insert into countries (cou_name, cou_flag) values ('Singapore', '🇸🇬');
insert into countries (cou_name, cou_flag) values ('Ivory Coast', '🇨🇮');
insert into countries (cou_name, cou_flag) values ('Kosovo', '🇽🇰');
insert into countries (cou_name, cou_flag) values ('Jersey', '🇯🇪');
insert into countries (cou_name, cou_flag) values ('Romania', '🇷🇴');
insert into countries (cou_name, cou_flag) values ('Slovenia', '🇸🇮');
insert into countries (cou_name, cou_flag) values ('Isle of Man', '🇮🇲');
insert into countries (cou_name, cou_flag) values ('Belarus', '🇧🇾');
insert into countries (cou_name, cou_flag) values ('Cuba', '🇨🇺');
insert into countries (cou_name, cou_flag) values ('Montserrat', '🇲🇸');
insert into countries (cou_name, cou_flag) values ('Montenegro', '🇲🇪');
insert into countries (cou_name, cou_flag) values ('Kiribati', '🇰🇮');
insert into countries (cou_name, cou_flag) values ('Liechtenstein', '🇱🇮');
insert into countries (cou_name, cou_flag) values ('Palau', '🇵🇼');
insert into countries (cou_name, cou_flag) values ('Réunion', '🇷🇪');
insert into countries (cou_name, cou_flag) values ('Saint Martin', '🇲🇫');
insert into countries (cou_name, cou_flag) values ('Pitcairn Islands', '🇵🇳');
insert into countries (cou_name, cou_flag) values ('Falkland Islands', '🇫🇰');
insert into countries (cou_name, cou_flag) values ('Sweden', '🇸🇪');
insert into countries (cou_name, cou_flag) values ('Hungary', '🇭🇺');
insert into countries (cou_name, cou_flag) values ('Morocco', '🇲🇦');
insert into countries (cou_name, cou_flag) values ('Colombia', '🇨🇴');
insert into countries (cou_name, cou_flag) values ('Sudan', '🇸🇩');
insert into countries (cou_name, cou_flag) values ('Hong Kong', '🇭🇰');
insert into countries (cou_name, cou_flag) values ('Saint Helena, Ascension and Tristan da Cunha', '🇸🇭');
insert into countries (cou_name, cou_flag) values ('Turkmenistan', '🇹🇲');
insert into countries (cou_name, cou_flag) values ('Togo', '🇹🇬');
insert into countries (cou_name, cou_flag) values ('Argentina', '🇦🇷');
insert into countries (cou_name, cou_flag) values ('Saudi Arabia', '🇸🇦');
insert into countries (cou_name, cou_flag) values ('Bermuda', '🇧🇲');
insert into countries (cou_name, cou_flag) values ('Ecuador', '🇪🇨');
insert into countries (cou_name, cou_flag) values ('Ethiopia', '🇪🇹');
insert into countries (cou_name, cou_flag) values ('Saint Kitts and Nevis', '🇰🇳');
insert into countries (cou_name, cou_flag) values ('Mauritius', '🇲🇺');
insert into countries (cou_name, cou_flag) values ('Netherlands', '🇳🇱');
insert into countries (cou_name, cou_flag) values ('Myanmar', '🇲🇲');
insert into countries (cou_name, cou_flag) values ('Cocos (Keeling) Islands', '🇨🇨');
insert into countries (cou_name, cou_flag) values ('Liberia', '🇱🇷');
insert into countries (cou_name, cou_flag) values ('Turks and Caicos Islands', '🇹🇨');
insert into countries (cou_name, cou_flag) values ('Tunisia', '🇹🇳');
insert into countries (cou_name, cou_flag) values ('Western Sahara', '🇪🇭');
insert into countries (cou_name, cou_flag) values ('Finland', '🇫🇮');
insert into countries (cou_name, cou_flag) values ('Iceland', '🇮🇸');
insert into countries (cou_name, cou_flag) values ('Northern Mariana Islands', '🇲🇵');
insert into countries (cou_name, cou_flag) values ('Guam', '🇬🇺');
insert into countries (cou_name, cou_flag) values ('Jamaica', '🇯🇲');
insert into countries (cou_name, cou_flag) values ('Burkina Faso', '🇧🇫');
insert into countries (cou_name, cou_flag) values ('Antigua and Barbuda', '🇦🇬');
insert into countries (cou_name, cou_flag) values ('Mongolia', '🇲🇳');
insert into countries (cou_name, cou_flag) values ('Benin', '🇧🇯');
insert into countries (cou_name, cou_flag) values ('Indonesia', '🇮🇩');
insert into countries (cou_name, cou_flag) values ('Georgia', '🇬🇪');
insert into countries (cou_name, cou_flag) values ('Albania', '🇦🇱');
insert into countries (cou_name, cou_flag) values ('Brazil', '🇧🇷');
insert into countries (cou_name, cou_flag) values ('Gibraltar', '🇬🇮');
insert into countries (cou_name, cou_flag) values ('Saint Vincent and the Grenadines', '🇻🇨');
insert into countries (cou_name, cou_flag) values ('Iran', '🇮🇷');
insert into countries (cou_name, cou_flag) values ('Portugal', '🇵🇹');
insert into countries (cou_name, cou_flag) values ('Cameroon', '🇨🇲');
insert into countries (cou_name, cou_flag) values ('Dominica', '🇩🇲');
insert into countries (cou_name, cou_flag) values ('Nigeria', '🇳🇬');
insert into countries (cou_name, cou_flag) values ('South Korea', '🇰🇷');
insert into countries (cou_name, cou_flag) values ('Angola', '🇦🇴');
insert into countries (cou_name, cou_flag) values ('Comoros', '🇰🇲');
insert into countries (cou_name, cou_flag) values ('Greece', '🇬🇷');
insert into countries (cou_name, cou_flag) values ('Belgium', '🇧🇪');
insert into countries (cou_name, cou_flag) values ('Puerto Rico', '🇵🇷');
insert into countries (cou_name, cou_flag) values ('Republic of the Congo', '🇨🇬');
insert into countries (cou_name, cou_flag) values ('Barbados', '🇧🇧');
insert into countries (cou_name, cou_flag) values ('Antarctica', '🇦🇶');
insert into countries (cou_name, cou_flag) values ('Equatorial Guinea', '🇬🇶');
insert into countries (cou_name, cou_flag) values ('Thailand', '🇹🇭');
insert into countries (cou_name, cou_flag) values ('Christmas Island', '🇨🇽');
insert into countries (cou_name, cou_flag) values ('Guinea-Bissau', '🇬🇼');
insert into countries (cou_name, cou_flag) values ('Panama', '🇵🇦');
insert into countries (cou_name, cou_flag) values ('Latvia', '🇱🇻');
insert into countries (cou_name, cou_flag) values ('Guyana', '🇬🇾');
insert into countries (cou_name, cou_flag) values ('Lithuania', '🇱🇹');
insert into countries (cou_name, cou_flag) values ('Yemen', '🇾🇪');
insert into countries (cou_name, cou_flag) values ('Martinique', '🇲🇶');
insert into countries (cou_name, cou_flag) values ('French Guiana', '🇬🇫');
insert into countries (cou_name, cou_flag) values ('Suriname', '🇸🇷');
insert into countries (cou_name, cou_flag) values ('United States Minor Outlying Islands', '🇺🇲');
insert into countries (cou_name, cou_flag) values ('Cyprus', '🇨🇾');
insert into countries (cou_name, cou_flag) values ('Cape Verde', '🇨🇻');
insert into countries (cou_name, cou_flag) values ('Wallis and Futuna', '🇼🇫');
insert into countries (cou_name, cou_flag) values ('Mayotte', '🇾🇹');
insert into countries (cou_name, cou_flag) values ('Vietnam', '🇻🇳');
insert into countries (cou_name, cou_flag) values ('French Polynesia', '🇵🇫');
insert into countries (cou_name, cou_flag) values ('Trinidad and Tobago', '🇹🇹');
insert into countries (cou_name, cou_flag) values ('Malawi', '🇲🇼');
insert into countries (cou_name, cou_flag) values ('Croatia', '🇭🇷');
insert into countries (cou_name, cou_flag) values ('Madagascar', '🇲🇬');
insert into countries (cou_name, cou_flag) values ('Armenia', '🇦🇲');
insert into countries (cou_name, cou_flag) values ('Austria', '🇦🇹');
insert into countries (cou_name, cou_flag) values ('Saint Pierre and Miquelon', '🇵🇲');
insert into countries (cou_name, cou_flag) values ('Afghanistan', '🇦🇫');
insert into countries (cou_name, cou_flag) values ('Central African Republic', '🇨🇫');
insert into countries (cou_name, cou_flag) values ('Zambia', '🇿🇲');
insert into countries (cou_name, cou_flag) values ('Bangladesh', '🇧🇩');
insert into countries (cou_name, cou_flag) values ('Costa Rica', '🇨🇷');
insert into countries (cou_name, cou_flag) values ('Faroe Islands', '🇫🇴');
insert into countries (cou_name, cou_flag) values ('Uganda', '🇺🇬');
insert into countries (cou_name, cou_flag) values ('Kazakhstan', '🇰🇿');
insert into countries (cou_name, cou_flag) values ('Bouvet Island', '🇧🇻');
insert into countries (cou_name, cou_flag) values ('South Georgia', '🇬🇸');
insert into countries (cou_name, cou_flag) values ('Tonga', '🇹🇴');
insert into countries (cou_name, cou_flag) values ('Ukraine', '🇺🇦');
insert into countries (cou_name, cou_flag) values ('Qatar', '🇶🇦');
insert into countries (cou_name, cou_flag) values ('Andorra', '🇦🇩');
insert into countries (cou_name, cou_flag) values ('Iraq', '🇮🇶');
insert into countries (cou_name, cou_flag) values ('Sri Lanka', '🇱🇰');
insert into countries (cou_name, cou_flag) values ('Japan', '🇯🇵');
insert into countries (cou_name, cou_flag) values ('Kyrgyzstan', '🇰🇬');
insert into countries (cou_name, cou_flag) values ('Philippines', '🇵🇭');
insert into countries (cou_name, cou_flag) values ('Pakistan', '🇵🇰');
insert into countries (cou_name, cou_flag) values ('British Indian Ocean Territory', '🇮🇴');


-- insert users (senhas: 123456)
insert into users (usr_name, usr_email, usr_password, usr_country_id, usr_score) values ('Felipe', 'felipe@email.com', '$2b$10$Be.y7oUVh6xWYTeHX.Nyh.7eJ3hR35gH47VYWH4ERmtFpX1fFVDke', 188, 532);
insert into users (usr_name, usr_email, usr_password, usr_country_id, usr_score) values ('Luis', 'luis@email.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', 188, 412);
insert into users (usr_name, usr_email, usr_password, usr_country_id, usr_score) values ('Willian', 'willian@email.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', 188, 1024);
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Fabíola', 'fabiola.castro@example.com', '$2b$10$Be.y7oUVh6xWYTeHX.Nyh.7eJ3hR35gH47VYWH4ERmtFpX1fFVDke', '243', '154');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Vanderléia', 'vanderleia.ferreira@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '251', '610');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Teodemiro', 'teodemiro.araujo@example.com', '$2b$10$Be.y7oUVh6xWYTeHX.Nyh.7eJ3hR35gH47VYWH4ERmtFpX1fFVDke', '148', '162');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Rufino', 'rufino.novaes@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '92', '405');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Silmara', 'silmara.castro@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '165', '209');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Dirque', 'dirque.ramos@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '117', '697');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Liana', 'liana.nogueira@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '228', '319');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Rubi', 'rubi.nascimento@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '9', '920');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Lucinda', 'lucinda.vieira@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '41', '1');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Guisela', 'guisela.alves@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '41', '185');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Durbalino', 'durbalino.viana@example.com', '$2b$10$Be.y7oUVh6xWYTeHX.Nyh.7eJ3hR35gH47VYWH4ERmtFpX1fFVDke', '225', '404');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Israel', 'israel.cavalcanti@example.com', '$2b$10$Be.y7oUVh6xWYTeHX.Nyh.7eJ3hR35gH47VYWH4ERmtFpX1fFVDke', '144', '766');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Zedeci', 'zedeci.moreira@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '104', '894');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Madail', 'madail.silva@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '215', '457');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Beritiana', 'beritiana.fernandes@example.com', '$2b$10$Be.y7oUVh6xWYTeHX.Nyh.7eJ3hR35gH47VYWH4ERmtFpX1fFVDke', '79', '582');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Janete', 'janete.freitas@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '91', '133');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Corsino', 'corsino.moura@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '169', '330');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Marialda', 'marialda.daluz@example.com', '$2b$10$Be.y7oUVh6xWYTeHX.Nyh.7eJ3hR35gH47VYWH4ERmtFpX1fFVDke', '222', '707');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Saúl', 'saul.silveira@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '100', '223');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Carlota', 'carlota.carvalho@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '3', '81');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Lénio', 'lenio.silveira@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '85', '102');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Iolene', 'iolene.freitas@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '216', '440');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Albenise', 'albenise.goncalves@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '110', '286');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Israelita', 'israelita.silveira@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '25', '509');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Augusto', 'augusto.silveira@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '70', '158');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Erasmo', 'erasmo.pereira@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '67', '225');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Enzo', 'enzo.dacunha@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '79', '632');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Zenira', 'zenira.araujo@example.com', '$2b$10$Be.y7oUVh6xWYTeHX.Nyh.7eJ3hR35gH47VYWH4ERmtFpX1fFVDke', '45', '59');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Flávia', 'flavia.lopes@example.com', '$2b$10$Be.y7oUVh6xWYTeHX.Nyh.7eJ3hR35gH47VYWH4ERmtFpX1fFVDke', '205', '566');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Élson', 'elson.silva@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '145', '62');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Bia', 'bia.dapaz@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '21', '420');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('José', 'jose.cardoso@example.com', '$2b$10$Be.y7oUVh6xWYTeHX.Nyh.7eJ3hR35gH47VYWH4ERmtFpX1fFVDke', '20', '904');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Betino', 'betino.farias@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '126', '38');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Idavide', 'idavide.dacruz@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '231', '292');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Veci', 'veci.silva@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '228', '794');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Tito', 'tito.dacosta@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '54', '956');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Leopoldo', 'leopoldo.damota@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '147', '143');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Loraci', 'loraci.martins@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '85', '60');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Anick', 'anick.silva@example.com', '$2b$10$Be.y7oUVh6xWYTeHX.Nyh.7eJ3hR35gH47VYWH4ERmtFpX1fFVDke', '92', '436');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Tércio', 'tercio.araujo@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '159', '640');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Anacleto', 'anacleto.darocha@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '218', '659');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Rui', 'rui.oliveira@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '240', '566');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Zelmira', 'zelmira.vieira@example.com', '$2b$10$Be.y7oUVh6xWYTeHX.Nyh.7eJ3hR35gH47VYWH4ERmtFpX1fFVDke', '33', '895');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Zelaci', 'zelaci.dasneves@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '107', '390');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Oceano', 'oceano.gomes@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '202', '390');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Ticiano', 'ticiano.porto@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '129', '278');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Roque', 'roque.mendes@example.com', '$2b$10$Be.y7oUVh6xWYTeHX.Nyh.7eJ3hR35gH47VYWH4ERmtFpX1fFVDke', '223', '156');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Primitivo', 'primitivo.damota@example.com', '$2b$10$Be.y7oUVh6xWYTeHX.Nyh.7eJ3hR35gH47VYWH4ERmtFpX1fFVDke', '43', '375');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Suzy', 'suzy.rocha@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '144', '643');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Sancler', 'sancler.gomes@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '120', '94');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Valdinélia', 'valdinelia.fogaca@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '100', '325');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Odeberto', 'odeberto.pinto@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '116', '976');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Maribel', 'maribel.ferreira@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '123', '453');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Clodomiro', 'clodomiro.aragao@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '114', '496');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Noara', 'noara.aragao@example.com', '$2b$10$Be.y7oUVh6xWYTeHX.Nyh.7eJ3hR35gH47VYWH4ERmtFpX1fFVDke', '77', '296');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Isaura', 'isaura.melo@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '33', '22');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Agostinho', 'agostinho.almeida@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '130', '77');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Graciela', 'graciela.porto@example.com', '$2b$10$Be.y7oUVh6xWYTeHX.Nyh.7eJ3hR35gH47VYWH4ERmtFpX1fFVDke', '186', '769');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Kate', 'kate.pereira@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '97', '272');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Jocélia', 'jocelia.araujo@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '137', '666');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Osvaldo', 'osvaldo.caldeira@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '229', '55');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Sabino', 'sabino.darosa@example.com', '$2b$10$Be.y7oUVh6xWYTeHX.Nyh.7eJ3hR35gH47VYWH4ERmtFpX1fFVDke', '248', '535');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Alba', 'alba.lopes@example.com', '$2b$10$Be.y7oUVh6xWYTeHX.Nyh.7eJ3hR35gH47VYWH4ERmtFpX1fFVDke', '27', '658');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Naod', 'naod.barros@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '80', '377');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Irma', 'irma.campos@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '190', '686');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Falcão', 'falcao.silveira@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '195', '916');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Jeremias', 'jeremias.sales@example.com', '$2b$10$Be.y7oUVh6xWYTeHX.Nyh.7eJ3hR35gH47VYWH4ERmtFpX1fFVDke', '21', '307');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Rúdi', 'rudi.araujo@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '103', '271');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Caroline', 'caroline.freitas@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '200', '330');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Grácio', 'gracio.ribeiro@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '182', '594');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Jéssica', 'jessica.caldeira@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '98', '775');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Betânia', 'betania.damota@example.com', '$2b$10$Be.y7oUVh6xWYTeHX.Nyh.7eJ3hR35gH47VYWH4ERmtFpX1fFVDke', '16', '435');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Graciela', 'graciela.moraes@example.com', '$2b$10$Be.y7oUVh6xWYTeHX.Nyh.7eJ3hR35gH47VYWH4ERmtFpX1fFVDke', '153', '457');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Rosilei', 'rosilei.araujo@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '251', '895');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Valdira', 'valdira.peixoto@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '147', '635');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Evelyni', 'evelyni.dapaz@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '46', '245');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Urbano', 'urbano.lima@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '43', '101');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Arlinda', 'arlinda.daconceicao@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '8', '939');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Prisca', 'prisca.cardoso@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '165', '880');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Fabíola', 'fabiola.moura@example.com', '$2b$10$Be.y7oUVh6xWYTeHX.Nyh.7eJ3hR35gH47VYWH4ERmtFpX1fFVDke', '142', '965');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Zilca', 'zilca.martins@example.com', '$2b$10$Be.y7oUVh6xWYTeHX.Nyh.7eJ3hR35gH47VYWH4ERmtFpX1fFVDke', '10', '560');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Firmino', 'firmino.oliveira@example.com', '$2b$10$Be.y7oUVh6xWYTeHX.Nyh.7eJ3hR35gH47VYWH4ERmtFpX1fFVDke', '17', '463');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Baltasar', 'baltasar.jesus@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '86', '364');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Elisângela', 'elisangela.costa@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '92', '76');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Ariadne', 'ariadne.barros@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '220', '870');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Ferdinando', 'ferdinando.dasneves@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '145', '700');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Seleni', 'seleni.nascimento@example.com', '$2b$10$Be.y7oUVh6xWYTeHX.Nyh.7eJ3hR35gH47VYWH4ERmtFpX1fFVDke', '228', '415');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Leonor', 'leonor.novaes@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '67', '367');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Cauani', 'cauani.pereira@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '21', '61');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Benete', 'benete.fogaca@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '33', '309');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Larissa', 'larissa.almeida@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '85', '412');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Nilce', 'nilce.souza@example.com', '$2b$10$Be.y7oUVh6xWYTeHX.Nyh.7eJ3hR35gH47VYWH4ERmtFpX1fFVDke', '3', '325');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Kailane', 'kailane.ramos@example.com', '$2b$10$eCFN.ZoLBL2dCgGGVMm49.46IuRhRdjSSQXw9m4AiBFgQEXJY06yO', '149', '569');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Rai', 'rai.rodrigues@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '240', '951');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Déborah', 'deborah.dacruz@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '120', '116');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Arcádio', 'arcadio.silva@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '103', '367');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Samaritano', 'samaritano.pinto@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '40', '13');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Claudilene', 'claudilene.teixeira@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '55', '172');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Dâni', 'dani.melo@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '2', '874');
INSERT INTO users (usr_name, usr_email, usr_password, usr_country_id, usr_score) VALUES ('Bridget', 'bridget.fogaca@example.com', '$2b$10$YvGa5pWprqtY1Yjr7mcan.G0yq5bT.hCjDbWHXCetDyyy.OBZ8QXa', '102', '561');


-- insert teams
insert into teams (tea_name, tea_description, tea_score) values ('Elite Runners', '...', 1438);
INSERT INTO teams (tea_name, tea_description, tea_score) VALUES ('Crystal Mammoth Squad', '...', 796);
INSERT INTO teams (tea_name, tea_description, tea_score) VALUES ('Brass Skull Riders', '...', 502);
INSERT INTO teams (tea_name, tea_description, tea_score) VALUES ('Demon Saber Clan', '...', 387);
INSERT INTO teams (tea_name, tea_description, tea_score) VALUES ('Diamond Wolf Tribe', '...', 1092);
INSERT INTO teams (tea_name, tea_description, tea_score) VALUES ('Blue Boar Soldiers', '...', 1739);
INSERT INTO teams (tea_name, tea_description, tea_score) VALUES ('Bronze Serpent Tribe', '...', 941);
INSERT INTO teams (tea_name, tea_description, tea_score) VALUES ('Scarlet Moth Riders', '...', 682);
INSERT INTO teams (tea_name, tea_description, tea_score) VALUES ('Razor Crew', '...', 417);
INSERT INTO teams (tea_name, tea_description, tea_score) VALUES ('Diamond Owl Riders', '...', 264);
INSERT INTO teams (tea_name, tea_description, tea_score) VALUES ('Black Wolf Squad', '...', 816);


-- team members
insert into team_members (tme_tea_id, tme_usr_id, tme_is_admin) values (1, 3, true);
insert into team_members (tme_tea_id, tme_usr_id) values (1, 1);
insert into team_members (tme_tea_id, tme_usr_id) values (1, 2);
insert into team_members (tme_tea_id, tme_usr_id, tme_is_admin) values (2, 4, true);
insert into team_members (tme_tea_id, tme_usr_id) values (2, 5);
insert into team_members (tme_tea_id, tme_usr_id) values (2, 6);
insert into team_members (tme_tea_id, tme_usr_id) values (2, 8);
insert into team_members (tme_tea_id, tme_usr_id) values (2, 9);
insert into team_members (tme_tea_id, tme_usr_id, tme_is_admin) values (3, 10, true);
insert into team_members (tme_tea_id, tme_usr_id) values (3, 11);
insert into team_members (tme_tea_id, tme_usr_id) values (3, 12);
insert into team_members (tme_tea_id, tme_usr_id) values (3, 13);
insert into team_members (tme_tea_id, tme_usr_id) values (3, 14);
insert into team_members (tme_tea_id, tme_usr_id) values (3, 15);
insert into team_members (tme_tea_id, tme_usr_id, tme_is_admin) values (4, 16, true);
insert into team_members (tme_tea_id, tme_usr_id) values (4, 17);
insert into team_members (tme_tea_id, tme_usr_id) values (4, 18);
insert into team_members (tme_tea_id, tme_usr_id) values (4, 19);
insert into team_members (tme_tea_id, tme_usr_id) values (4, 20);
insert into team_members (tme_tea_id, tme_usr_id) values (4, 21);
insert into team_members (tme_tea_id, tme_usr_id, tme_is_admin) values (5, 22, true);
insert into team_members (tme_tea_id, tme_usr_id) values (5, 23);
insert into team_members (tme_tea_id, tme_usr_id) values (5, 24);
insert into team_members (tme_tea_id, tme_usr_id) values (5, 25);
insert into team_members (tme_tea_id, tme_usr_id) values (5, 26);
insert into team_members (tme_tea_id, tme_usr_id) values (5, 27);
insert into team_members (tme_tea_id, tme_usr_id, tme_is_admin) values (6, 28, true);
insert into team_members (tme_tea_id, tme_usr_id) values (6, 29);
insert into team_members (tme_tea_id, tme_usr_id) values (6, 30);
insert into team_members (tme_tea_id, tme_usr_id) values (6, 31);
insert into team_members (tme_tea_id, tme_usr_id) values (6, 32);
insert into team_members (tme_tea_id, tme_usr_id) values (6, 33);
insert into team_members (tme_tea_id, tme_usr_id, tme_is_admin) values (7, 34, true);
insert into team_members (tme_tea_id, tme_usr_id) values (7, 35);
insert into team_members (tme_tea_id, tme_usr_id) values (7, 36);
insert into team_members (tme_tea_id, tme_usr_id) values (7, 37);
insert into team_members (tme_tea_id, tme_usr_id) values (7, 38);
insert into team_members (tme_tea_id, tme_usr_id) values (7, 39);
insert into team_members (tme_tea_id, tme_usr_id, tme_is_admin) values (8, 40, true);
insert into team_members (tme_tea_id, tme_usr_id) values (8, 41);
insert into team_members (tme_tea_id, tme_usr_id) values (8, 42);
insert into team_members (tme_tea_id, tme_usr_id) values (8, 43);
insert into team_members (tme_tea_id, tme_usr_id) values (8, 44);
insert into team_members (tme_tea_id, tme_usr_id) values (8, 45);
insert into team_members (tme_tea_id, tme_usr_id, tme_is_admin) values (9, 46, true);
insert into team_members (tme_tea_id, tme_usr_id) values (9, 47);
insert into team_members (tme_tea_id, tme_usr_id) values (9, 48);
insert into team_members (tme_tea_id, tme_usr_id) values (9, 49);
insert into team_members (tme_tea_id, tme_usr_id) values (9, 50);
insert into team_members (tme_tea_id, tme_usr_id) values (9, 51);
insert into team_members (tme_tea_id, tme_usr_id, tme_is_admin) values (10, 52, true);
insert into team_members (tme_tea_id, tme_usr_id) values (10, 53);
insert into team_members (tme_tea_id, tme_usr_id) values (10, 54);
insert into team_members (tme_tea_id, tme_usr_id) values (10, 55);
insert into team_members (tme_tea_id, tme_usr_id) values (10, 56);
insert into team_members (tme_tea_id, tme_usr_id) values (10, 57);
insert into team_members (tme_tea_id, tme_usr_id, tme_is_admin) values (11, 58, true);
insert into team_members (tme_tea_id, tme_usr_id) values (11, 59);
insert into team_members (tme_tea_id, tme_usr_id) values (11, 60);
insert into team_members (tme_tea_id, tme_usr_id) values (11, 61);
insert into team_members (tme_tea_id, tme_usr_id) values (11, 62);
insert into team_members (tme_tea_id, tme_usr_id) values (11, 63);


commit;
